import { NextRequest, NextResponse } from 'next/server';

interface DeployRequest {
  html: string;
  componentCode: string;
  cssCode: string;
  title: string;
  pageType: string;
}

export async function POST(req: NextRequest) {
  try {
    const body: DeployRequest = await req.json();
    const { componentCode, cssCode, title } = body;

    const vercelToken = process.env.VERCEL_DEPLOY_TOKEN;
    if (!vercelToken) {
      return NextResponse.json(
        { error: 'Vercel deploy token not configured. Add VERCEL_DEPLOY_TOKEN to your .env.local' },
        { status: 401 }
      );
    }

    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 40);

    const projectName = `shopforge-${slug}-${Date.now().toString(36)}`;

    const safeTitle = JSON.stringify(title);

    const files = [
      {
        file: 'package.json',
        data: JSON.stringify(
          {
            name: projectName,
            version: '0.1.0',
            private: true,
            scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
            dependencies: { next: '14.0.0', react: '^18', 'react-dom': '^18' },
            devDependencies: {
              tailwindcss: '^3',
              autoprefixer: '^10',
              postcss: '^8',
              '@types/node': '^20',
              '@types/react': '^18',
              typescript: '^5',
            },
          },
          null,
          2
        ),
      },
      {
        file: 'next.config.js',
        data: `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;`,
      },
      {
        file: 'tailwind.config.js',
        data: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
};`,
      },
      {
        file: 'postcss.config.js',
        data: `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };`,
      },
      {
        file: 'src/app/globals.css',
        data: `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${cssCode}`,
      },
      {
        file: 'src/app/layout.tsx',
        data: `import './globals.css';\nimport type { Metadata } from 'next';\n\nexport const metadata: Metadata = {\n  title: ${safeTitle},\n  description: 'Generated by ShopForge',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}`,
      },
      {
        file: 'src/app/page.tsx',
        data: `import App from '../components/App';\nexport default function Page() { return <App />; }`,
      },
      {
        file: 'src/components/App.tsx',
        data: `'use client';\nimport React from 'react';\n\n${componentCode.replace(/^function App/, 'export default function App')}`,
      },
    ];

    const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: projectName,
        files: files.map((f) => ({
          file: f.file,
          data: Buffer.from(f.data).toString('base64'),
          encoding: 'base64',
        })),
        projectSettings: {
          framework: 'nextjs',
          buildCommand: 'next build',
          outputDirectory: '.next',
        },
        target: 'production',
      }),
    });

    const deployData = await deployResponse.json();

    if (!deployResponse.ok) {
      console.error('Vercel deploy error:', deployData);
      return NextResponse.json(
        { error: deployData.error?.message || 'Deployment failed. Check your Vercel token.' },
        { status: 500 }
      );
    }

    const deployUrl = `https://${deployData.url}`;

    return NextResponse.json({
      url: deployUrl,
      deploymentId: deployData.id,
      readyState: deployData.readyState,
    });
  } catch (error) {
    console.error('Deploy error:', error);
    return NextResponse.json({ error: 'Deployment failed. Please try again.' }, { status: 500 });
  }
}
